version: '3'
services:
  blogdupe-frontend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NEXT_PUBLIC_PRODUCTION_ENDPOINT=${NEXT_PUBLIC_PRODUCTION_ENDPOINT}
      - PORT=${PORT}
